name: Varbase AI - Default
description: A recipe to manage default installed modules, configs and permissions.
type: install
install:
  - ai
  - ai_provider_openai
  - ai_image_alt_text
  - ai_automators
  - ai_ckeditor
config:
  import:
    ai: '*'
    ai_image_alt_text: '*'
    ai_automators: '*'
    ai_ckeditor: '*'
  actions:
    user.role.site_admin:
      grantPermissions:
        - 'generate ai alt tags'
        - 'use ai ckeditor'
    user.role.content_admin:
      grantPermissions:
        - 'generate ai alt tags'
        - 'use ai ckeditor'
    user.role.editor:
      grantPermissions:
        - 'generate ai alt tags'
        - 'use ai ckeditor'
