name: Varbase AI - Default
description: A recipe to manage default installed modules, configs and permissions.
type: install
install:
  - openai
  - openai_ckeditor
  - openai_content
  - ai_interpolator
  - ai_interpolator_openai
config:
  actions:
    user.role.site_admin:
      grantPermissions:
        - 'access openai content tools'
        - 'use openai ckeditor'
    user.role.content_admin:
      grantPermissions:
        - 'access openai content tools'
        - 'use openai ckeditor'
    user.role.editor:
      grantPermissions:
        - 'access openai content tools'
        - 'use openai ckeditor'
